// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSe_lIA8nqzZmJCV50iVn4cJFPdrhFX8',
    appId: '1:320254286922:web:24206affc0cfc3060c1ab3',
    messagingSenderId: '320254286922',
    projectId: 'inventory-c43c0',
    authDomain: 'inventory-c43c0.firebaseapp.com',
    databaseURL: 'https://inventory-c43c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-c43c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72G4i1GXps8kE33oKwu-3sGfTw8CztUQ',
    appId: '1:320254286922:android:69feec27f9f872170c1ab3',
    messagingSenderId: '320254286922',
    projectId: 'inventory-c43c0',
    databaseURL: 'https://inventory-c43c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-c43c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuXDc-FkujMfEl5EfYF6A-MfjvruartuM',
    appId: '1:320254286922:ios:776c187353846fb70c1ab3',
    messagingSenderId: '320254286922',
    projectId: 'inventory-c43c0',
    databaseURL: 'https://inventory-c43c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-c43c0.appspot.com',
    iosBundleId: 'com.example.listApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuXDc-FkujMfEl5EfYF6A-MfjvruartuM',
    appId: '1:320254286922:ios:776c187353846fb70c1ab3',
    messagingSenderId: '320254286922',
    projectId: 'inventory-c43c0',
    databaseURL: 'https://inventory-c43c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-c43c0.appspot.com',
    iosBundleId: 'com.example.listApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfSe_lIA8nqzZmJCV50iVn4cJFPdrhFX8',
    appId: '1:320254286922:web:da928ee4b4b640290c1ab3',
    messagingSenderId: '320254286922',
    projectId: 'inventory-c43c0',
    authDomain: 'inventory-c43c0.firebaseapp.com',
    databaseURL: 'https://inventory-c43c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-c43c0.appspot.com',
  );

}